# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Snapchat Clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Snapchat Clone
  # Add the Firebase pod for Google Analytics
  pod 'FirebaseAnalytics'

  # For Analytics without IDFA collection capability, use this pod instead
  # pod ‘Firebase/AnalyticsWithoutAdIdSupport’

  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'

  target 'Snapchat CloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Snapchat CloneUITests' do
    # Pods for testing
  end

end
